### PR TITLE
add option not to use pcrecpp

### PR DESCRIPTION
**Pull request by k-okada**
I still have trouble on #7 and it seems something trouble if we load collada-dom vid dlopen and host program already have liked with pcre library
This PR rewrite function using pcrecpp, and confirmed it works on test code fixed in #11

### CODE REVIEW

**Comment by 130s** [comment]
ping @rdiankov

**Comment by k-okada** [comment]
this can be resolved in https://github.com/ros/robot_model/pull/108

--
◉ Kei Okada

**Comment by rdiankov** [comment]
oops, i thought i had merged this. thanks for the pull request!

i just made a minor commit to fallback on pcrecpp

5939c33774ec531193a1d37a9fb52c2c2d4dec8a

**Comment by k-okada** [comment]
thanks, merging this it's self is ok, but to be effective on ros users,
1. update openrave launchpad 
2. ask tully? to copy that launch pad deb to package.ros.org 

--
◉ Kei Okada

**Pull request merged**
