### PR TITLE
- force to use local_pcre and change namespace to use them

### PR DESCRIPTION
**Pull request by k-okada**
I think we need either #12 or #13 to be merged.

### CODE REVIEW

**Comment by 130s** [comment]
What's the status of this?
This PR seems to be required in a downstream package I maintain (https://github.com/start-jsk/rtmros_hironx/issues/202#issuecomment-88307393). I can do testing next week if that helps.
Thanks!

**Comment by rdiankov** [comment]
now that liburiparser is added to CMakeLists.txt, there should be no need for libpcrecpp... so i thought this issue was closed...

**Comment by 130s** [comment]
> #12 solves "MY" problem, but it may bring new trouble, #13 is more confident, I think.

Given the comment above from @k-okada, I thought we might want to merge #13 (this PR) but I might be wrong.

**Comment by k-okada** [comment]
#12 solved this

**Pull request closed without merging**
